### PR TITLE
Updates Try this

### PR DESCRIPTION
**Pull request by broken1arrow**
I had to manually edit the java files. I hope I not miss something i changed. My idea seams to change hole class when I change code. 

I don´t know how to fix that problem, but I hope this will work for you to check what you thing of the changes. I has more to fix, but will be hard to do if I can´t do it inside idea.

### CODE REVIEW

**Comment by broken1arrow** [comment]
I think it complain on I has not fix one import, but are harder to edit java this way.

I has only find out it is My idea some update whole class, so seams like it is impossible to stop this behavior. I has to see if I can instead add that rubbish to other branch and hope that fix the issue.

**Comment by pop4959** [comment]
Just a heads-up that the build is currently failing.

**Comment by broken1arrow** [comment]
> Just a heads-up that the build is currently failing.

Yes i is 99% is the location import missing in db class.
This one.
src/main/java/com/griefcraft/sql/PhysDB.java

I find out is issue to use my idea (intelj) with github desktop it refreshing whole class when adding code for first time. So for you get right data i has want to try to add that update to other branch to fix that import.

But the i want from you is input on my code changes.

**Comment by broken1arrow** [comment]
> Just a heads-up that the build is currently failing.

So if that import. But i can´t work like this. I use right now microsoft notepad for add right changes. But if I try do it inside idea 
I get this mess https://github.com/broken1arrow/LWCX/commit/d23fb883841d40b27235b178592abc6b65cb9ceb .

So I don´t know how I shall progress on update your permissions. As it is now is it nearly a impossible to work with this projekt. So after this changes I will not update from ether find a fix or I can´t work with this sadly. Or has to use paste bin or something, Is to messy to edit the files direly with out any coding software.

**Comment by pop4959** [comment]
I'm curious as to why you aren't using an IDE for this, but regardless, since it sounds like you're not able to make more progress on this I'll go ahead and close this PR. Feel free to open a new one if you find a better solution to your problems.

**Comment by broken1arrow** [comment]
> I'm curious as to why you aren't using an IDE for this, but regardless, since it sounds like you're not able to make more progress on this I'll go ahead and close this PR. Feel free to open a new one if you find a better solution to your problems.

Because the mess I create and you don´t like I import whole class ether. Has no idea way it do like so for me.

Ether way has fixed the error and I will ofc try fix this but right now I´m sick on GitHub refuse me from work on your plugin :/

The I has made shall be full working, but I only wanted you review it and give input. So i know How I shall move on with my changes.

**Pull request closed without merging**
