### PR TITLE
use persistent data container to save protection info

### PR DESCRIPTION
**Pull request by cs8425**
As title,
this PR try to save protection block info into `org.bukkit.persistence.PersistentDataContainer`,
then we can reduce some SQLite/RDBMS usage.
Maybe we can even drop RDBMS dependency if only want the 'protection part'...?

### CODE REVIEW

**Comment by pop4959** [comment]
Thanks for the PR. Been meaning to look into PDC for a while. It definitely can help quite a bit if done correctly. This looks like a good start.

I have glanced over the code, but maybe you can give me a brief description of the design and some of the implementation choices you made going into this. I'd like to have a better understanding before reviewing this further.

There are also some actions which are rather difficult to do without saving to a centralized location (namely queries to many/all protections in the world). Is that accounted for?

You've also mentioned that you are trying to include this in the SQLite/MySQL implementations, however have you considered making it a new database type entirely? We would need to address the above questions but this might be the best solution for people looking for better performance since we can avoid using the other databases entirely.

**Comment by cs8425** [comment]
> I have glanced over the code, but maybe you can give me a brief description of the design and some of the implementation choices you made going into this. I'd like to have a better understanding before reviewing this further.

Sorry for my bad English first,
I will try explain as clear as I can.

Currently, it will try using PDC (to read/write protection info) first,
if block/entity can't support PDC, then fail back to the original method (SQLite/MySQL).
So, I find out the entrance and hook/change the necessary parts:
* any thing try to get protection info ( `PhysDB#resolveProtection()` `PhysDB#loadProtection()`), build protection from PDC
* create new protection ( `PhysDB#registerProtection()` ), and write to PDC
* if get/create protection info base on location, try modify to base on block (still using cache for some lookup by location)
* save protection (`Protection#save()` `Protection#saveNow()`), try write back to PDC of that block
* remove protection (`Protection#remove()`), try clear data in PDC of that block
* PDC only save necessary info: `id` `type` `owner` `password` `date` `last_accessed` `JSON_data`
    * `id` for compatible DB's ID, save in `pdc.yml`, goes negative

> There are also some actions which are rather difficult to do without saving to a centralized location (namely queries to many/all protections in the world). Is that accounted for?

No, because nearly no protection info save into db, those features (eg: history) will not work correctly...
May need to design something for those features.
Or just disable them if people just want the 'protection parts'.
 
> You've also mentioned that you are trying to include this in the SQLite/MySQL implementations, however have you considered making it a new database type entirely? We would need to address the above questions but this might be the best solution for people looking for better performance since we can avoid using the other databases entirely.

Sorry, I can't clearly understand what you means.
I would like to:
* only use PDC (and some file based KV/list if needed), but:
    * some protection seems can't save to PDC
    * some features not compatible
* so:
    * disable/skip them
    * only use SQLite/MySQL for some non-compatible features (may need more works and may have more issues)
    * or other saving method?

Actually, because it seems there are no protection plugin base on PDC currently,
I had try to create a new plugin for single block protection with auto remove protection if owner not online for XXX days (protection parts base on PDC, and auto remove parts base on a list/table in yml).
But there are so many event to check, I can't complete it in short time, at least I need a usable protection plugin on my server.
So I modify LWC to be sure that protection base on PDC is possible and usable.
Thanks all of you build this great plugin :)

**Comment by pop4959** [comment]
Ah I see. Thanks for the explanation. Yeah there are several issues that probably need to be worked out first then. What I'm most worried about is that PDC replaces the SQLite/MySQL implementation to such a large degree that it will make non-backwards-compatible changes (so using another version of LWC or trying to migrate the database would not work properly).

What I meant by making a "new database" was in the configuration (core.yml) for the database where you specify "sqlite" or "mysql" you could instead write "pdc" and have a completely 100% PDC implementation (perhaps with some supporting files since some actions cannot be done fully with PDC). Then we don't have to worry about the changes causing problems for SQLite/MySQL users.

**Comment by cs8425** [comment]
OK, I think I will add two configuration:
* `database.usePDC`: true/false
* `database.onlyPDC`: true/false

if `database.usePDC = false`, will just behave as normal.
if `database.usePDC = true` and `database.onlyPDC = true`, will only use PDC and disable some non-compatible features.
if `database.usePDC = true` and `database.onlyPDC = false`, will try to use PDC first and failback to SQLite/MySQL, this will keep old protection work and new protection will be save in PDC just like `database.onlyPDC = true`.

So new users can use ~100% PDC, and SQLite/MySQL users can change to PDC without lost old protection, if they don't need some non-compatible features.

BTW, do we have some better testing method?
for checking different player can access or not, and/or all functions work.

**Comment by pop4959** [comment]
Closing this as I don't really have any intent of merging it in its current state. There's too much extra complexity here when considering that this is being mixed into the SQLite/MySQL implementations and makes a non-backwards compatible change with high risk of breaking some features in LWC (especially related to lookups).

**Pull request closed without merging**
