### PR TITLE
Support new Factions code

### PR DESCRIPTION
**Pull request by animeavi**
This does not appear to be released in the Spigot plugins page but the Maven repo already has this version (1.6.9.5-U0.4.9).

### CODE REVIEW

**Comment by pop4959** [comment]
Is it a breaking change? If so, perhaps consider adding some sort of compatibility with the older version (especially since this is targeting an unreleased development build of Factions), or if that is not possible, a message stating that the server should update the plugin. Otherwise, this looks good to me, and if you've already tested it I will pull it in straight away.

**Comment by animeavi** [comment]
I tested it but I'll try to figure out something to stay compatible with older releases.

**Comment by animeavi** [comment]
So I have this atm to support old and new versions, problem is that it doesn't work.
Any help getting this to work properly would be appreciated.
https://github.com/animeavi/LWCX/commits/factions

Specifically, I'm not sure how to handle the two conflicting JARs and make it not give me compile errors, if even possible.

**Comment by pop4959** [comment]
Yeah, package names must be unique, and they are not going to be if you are trying to build against two copies of the same library/plugin. I would also not make a separate FactionsLegacy class. I think you can still keep the code in one place.

If the version string for factions is easy to decipher, you could use an if/else to determine whether to run the code based on a minimum version threshold.

Another option (which is a bit hacky, and fragile, but I've seen in some other plugins) is to use `Class.forName("com.package.Classname");` to see if a new class was added/removed in that version, and use a try/catch block to run appropriate code depending on if it throws ClassNotFoundException.

Otherwise, you might want to consult the Factions devs directly and ask what else you could try.

**Comment by animeavi** [comment]
I was mostly trying separate classes with the illusion that it would solve the import errors but wasn't so lucky. I'll what else I can try.

**Comment by animeavi** [comment]
Ok I have added support for the old code too with some reflection magic, but it's not as good as I wanted it to be.

At the moment it will _only_ check if you're a faction member, meaning it doesn't check if build permissions are denied for you, and it can't also allow members of other factions to protect blocks in your Faction if you also allow them to build, which isn't a huge problem but it's what the original code did. I'm not even sure if the old code is possible to be re-implemented using reflection, so this is what I got for now.

**Comment by pop4959** [comment]
Yeah, it's a bit tricky, and I don't have much expertise in this area either. I think checking the zones and membership in a faction will probably be good enough for backwards compatibility. The idea I have is that most people will be updating to the latest version of Factions eventually anyway, but this will help prevent people from complaining that LWC's integration is broken.

I may look into this more later out of personal interest to see if I can manage to clean it up any more. However, I think the code is clear and I like especially that you separated the compatibility code into its own method. Keeps things from getting tangled up in there.

**Pull request merged**
