### PR TITLE
Alright I think this will work

### PR DESCRIPTION
**Pull request by broken1arrow**
as I say On discord do you want to keep all this ?

`LRUCache<Integer, Protection> cache = new LRUCache<Integer, Protection>(1000 * 100)`

Ether way have finally get it work. Give input on this and I will fix that and has some own plans to improve the code, but will fix that after what you say about the changes.

### CODE REVIEW

**Comment by pop4959** [comment]
I don't really think adding even more permission checks everywhere on top of what already exists is going to make anything much better, if anything it adds further complexity to a system that is already quite confusing.

On top of that, for most of these I'm pretty sure `lwc.mod` and `lwc.admin` already work for these use cases.

**Comment by broken1arrow** [comment]
> I don't really think adding even more permission checks everywhere on top of what already exists is going to make anything much better, if anything it adds further complexity to a system that is already quite confusing.
> 
> On top of that, for most of these I'm pretty sure `lwc.mod` and `lwc.admin` already work for these use cases.

The problem is the current system are not up to date and one permission are missing inside plugin.yml (some already exist in the code).

The biggest problem with only lwc.mod and lwc.admin is mods can´t break chest. So My idea was to make it more dynamic (so you can self add or deny perms as you want). I mean most of my server don't need reload or open admin chest, but need access so they can remove other players chest or other things.

I have done so it not break your old system and I could make it cleaner (but for I shall spend times, is if you are interested in changes ).

They can still only use  `lwc.mod` and `lwc.admin`  if they want to, but also have option to add other permissions.

**Comment by pop4959** [comment]
Permissions missing from plugin.yml isn't crucial, but that could certainly be fixed in a separate PR to make it easier for plugins like LuckPerms to find permission nodes.

As for breaking chests, `lwc.mod` is *not* supposed to be able to break chests, as this is considered an admin action (removing players protections). If you want someone to be able to break chests, you should probably be fine with them being an LWC admin.

The main problem I have with this is that even though it is backwards compatible, it's super confusing (as I already mentioned) so it makes little sense to try to improve, without ripping everything apart and completely redoing the entire thing, which will obviously require a lot more work and careful thinking.

It would still need to be backwards compatible since breaking everyone's existing permission setups is a huge nope.

**Comment by broken1arrow** [comment]
> Permissions missing from plugin.yml isn't crucial, but that could certainly be fixed in a separate PR to make it easier for plugins like LuckPerms to find permission nodes.
> 
> As for breaking chests, `lwc.mod` is _not_ supposed to be able to break chests, as this is considered an admin action (removing players protections). If you want someone to be able to break chests, you should probably be fine with them being an LWC admin.
> 
> The main problem I have with this is that even though it is backwards compatible, it's super confusing (as I already mentioned) so it makes little sense to try to improve, without ripping everything apart and completely redoing the entire thing, which will obviously require a lot more work and careful thinking.
> 
> It would still need to be backwards compatible since breaking everyone's existing permission setups is a huge nope.

Like I done it It not break players current setup and no I not add any perms to  `lwc.mod` he not had before (but with option to add other perms admin have). 

We all use different setup for mod and admin and a plugin should not limit option how you want it on the server (when I made my own plugin I try to not hard code anything (if I not have other option or not useful for end user to change x value)).

mod´s i give lots of perms, but they not have file access so reload and similar thing are not useful for mods to have access too. 

How i don it, you can give option for mods to break other players protection, but not admins.

**Comment by pop4959** [comment]
Yeah I understand that it doesn't break anyone's set up, but it's still a hack, as I've mentioned twice already, and this really aught to be completely re-done properly (with backwards compatibility with the old permission nodes).

More flexibility is always good.

**Comment by pop4959** [comment]
If you open a new PR which does this properly I'll consider merging it.

**Pull request closed without merging**
