### PR TITLE
Permissions changes and added one api method location

### PR DESCRIPTION
**Pull request by broken1arrow**
Sry is like a mess, but is how github has done it and I has to fix my GitHub Desktop because it break on last pull to my fork :/

Ether way added. 
```	public Protection loadProtection(String worldName, Location location) {
		return loadProtection(worldName, location.getBlockX(), location.getBlockY(), location.getBlockZ(), false);
	} 
```
and perms and used your hasperm method.

### CODE REVIEW

**Comment by broken1arrow** [comment]
Has now fix it, you can check my last https://github.com/pop4959/LWCX/pull/179/commits/29968b451004bb5ad280854ecb2b4b41452473b2 for the changes I has done. 

I don´t know I if I shall re upload it with only the changes. So you can more easy to see what I has change. get little weird when set it up first time (I don´t do it right).

**Comment by pop4959** [comment]
Please fix the diff before asking me to review this, and give a clear explanation of what you are changing here.

**Comment by broken1arrow** [comment]
Sad thing i can't fix this easy. But will try fix it up later i don't know way it not allowed me to only pull one comment.

**Comment by broken1arrow** [comment]
Yeah I can´t fix this issue. I not allow me to only move one commit to new branch. So has to remove it on github and redo the code. is impossible to fix this mess.

**Comment by broken1arrow** [comment]
I try redo the work but still it refresh hole class. I don't know way. I download the source from my fork and upload it to idea and still not work as it should

**Comment by broken1arrow** [comment]
I Think I cant fix for now soo only was is to show my changes manually. Can have miss something but gitub refuse to not add all methods in the class, no mater what I has try. 

Has try remove and add the fork but that not work at all and add it back to idea. I can´t get it to work as I want.

Is when you access protection and added so you can use perms for it.
https://pastebin.com/HBaLB9Tg

Make so you can break a protected chest with lwc.force.destroy.block perm.
https://pastebin.com/TQ2iK6Jn

Inside plugin yaml

I added perms like this 

``` 
  lwc.admin:
    description: Gives you absolutely power over LWC. As an LWC admin, you have no restrictions.
    default: false
    children:
      lwc.protect.bypass: true
      lwc.allcommands: true
      
      # description: allows you to remove protection
      lwc.admin.remove: true
      # description: allows you to open containers/inventorys
      lwc.bypass.access.protection: true
      # description: allows you to destroy containers
      lwc.force.destroy.block: true
      # description: allows you to administrate a protection
      lwc.administrate.protection: true
     # description: allows you to open admin chest.
      lwc.bypass.access.only.admin: true

  lwc.mod:
    description: Allows you to open anyone's protection but not remove them
    default: false
    children:
      lwc.protect.bypass: true
      # description: allows you to open containers/inventorys
      lwc.bypass.access.protection: true
  
```
https://pastebin.com/HLyej6kU

**Pull request closed without merging**
